### pedir todos los usuarios
GET http://localhost:3001/users

### crear un usuario

POST http://localhost:3001/users
Content-Type: application/json

{
    "userName": "juan5",
    "email":"pepte@hotmail.com",
    "password":"12345hahah"
}
### verificar si existe un usuario con el usuerName y password correcta 

GET  http://localhost:3001/user
Content-Type: application/json

{
    "userName": "pepe24",
    "password":"12345678"
}