### pedir todos los usuarios
GET http://localhost:3001/users

### crear un usuario
POST http://localhost:3001/users
Content-Type: application/json

{
    "userName": "juan5",
    "email":"pepte@hotmail.com",
    "password":"12345hahah"
}
### verificar si existe un usuario con el usuerName y password correcta 

GET  http://localhost:3001/user
Content-Type: application/json

{
    "userName": "pepe24",
    "password":"12345678"
}

### teste creando user en db

POST https://h-chat.onrender.com/login
Content-Type: application/json

{
    "user": "penanieto26",
   "password":"Pene123456"
}

### creando user en bd desde el local
POST http://localhost:42066/users
Content-Type: application/json

{
    "user": "juana666",
    "correo":"jyana666@hotmail.com",
    "password":"12345asdfa"
}

### creando user en bd desde el servidor
POST https://localhost:42066/login
Content-Type: application/json

{
    "user": "killua",
    "password":"Somoslejion360"
}



###xe
POST  https://msgchatenshi-default-rtdb.firebaseio.com/mschat.json
Content-Type: application/json

{
    "city": "Tampa",
    "country": "FLORIDA",
    "msg": "nub",
    "region": "NY",
    "user": "[-----]"
}